// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://saxakqifautnkreqjtbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNheGFrcWlmYXV0bmtyZXFqdGJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxNjk4NTEsImV4cCI6MjA3Nzc0NTg1MX0.sJww9tkAdG6UfExobx7-KA-8RK2znXviyqB89lE_aGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});